### PR TITLE
[MRG] Add help text to all commands

### LINKED ISSUE #23: Add help text to all commands
https://click.palletsprojects.com/en/7.x/documentation/#help-texts

### PR DESCRIPTION
**Pull request by JosemyDuarte**
I have added some messages to the commands and also to the options. The only one missing is on `remind -i` bc I wasn't sure about what would be a good description for that option. I am open to any suggestions to update my PR.

### CODE REVIEW

**Comment by vinayak-mehta** [comment]
@JosemyDuarte For `remind -i`, we can put "Conference identifier" maybe, what do you think?

**Comment by vinayak-mehta** [comment]
Apart from the minor change, everything else looks good!

**Comment by JosemyDuarte** [comment]
Cool @vinayak-mehta! I have capitalized the first letter and added the missing description.

**Comment by vinayak-mehta** [comment]
Thanks for the contribution!

**Pull request merged**
