### PR TITLE
[MRG] Add scrapper for PyData

### PR DESCRIPTION
**Pull request by CristhianMotoche**
## Notes
- I added tests for it
- I integrated the project with travis
- I moved the scrapers inside `conrad` so that we can encapsulate those functionalities.

### CODE REVIEW

**Comment by vinayak-mehta** [comment]
@CristhianMotoche Thanks for the awesome PR! I'll review it today :)

**Comment by vinayak-mehta** [comment]
@CristhianMotoche The scraper looks good to me, can you me push access to this branch on your fork so that I can make some changes before merging the PR?

**Comment by vinayak-mehta** [comment]
@CristhianMotoche Can you please structure your crawler as mentioned in the docs? https://conference-radar.readthedocs.io/en/latest/dev/adding-crawlers.html

**Comment by CristhianMotoche** [comment]
Hello @vinayak-mehta Please, let me know it if looks good now. BTW, I had to add the dependencies from `requirements-crawl.txt` to `dev_requirements` in the `setup.py` so that it downloads those dependencies when executing `pip install ".[dev]"`.

**Comment by vinayak-mehta** [comment]
Thanks for updating the PR! I'll check it out today :)

**Comment by vinayak-mehta** [comment]
Hey made some fixes, please apply the patch attached with this comment.

- Removed Travis and tests (these can be separate PRs)
- Added BaseCrawler usage
- Blackened code

Please apply the patch, push your changes the and PR should be good to go! :)

[pydata-crawler.zip](https://github.com/vinayak-mehta/conrad/files/3808194/pydata-crawler.zip)

**Comment by CristhianMotoche** [comment]
Hello @vinayak-mehta Sure! I'll try to do it today before the end of the day. Thanks for the suggestions.

**Comment by vinayak-mehta** [comment]
I'll merge this and apply the patch, thanks for the contribution!

**Pull request merged**
